name: Build Chrome Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      #- name: Setup Node.js
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: '18'
      #    cache: 'npm'

      #- name: Install dependencies
      #  run: npm ci

      #- name: Run tests
      #  run: npm test || true

      - name: Create build directory
        run: mkdir -p dist

      - name: Copy extension files
        run: |
          rsync -av --progress ./ ./dist/ \
          --exclude=".git" \
          --exclude=".github" \
          --exclude="node_modules" \
          --exclude="tests" \
          --exclude="*.md" \
          --exclude=".gitignore" \
          --exclude="package-lock.json" \
          --exclude="dist" \
          --exclude=".vscode" \
          --exclude="*.log" \
          --exclude="*.test.js" \
          --exclude="__mocks__" \
          --exclude="coverage"

      - name: Build extension
        run: |
          cd dist
          npm run build || true

      - name: Package extension
        run: |
          cd dist
          zip -r ../chrome-extension.zip .

      - name: Upload extension package
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: chrome-extension.zip
          if-no-files-found: error